server:
  port: 9999
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://144.24.88.33:3306/mannayo
    username: okane
    password: opi7opi7opi7@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect