name: SSH Action Example

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set YML
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.SECRET_APPLICATION }}" | base64 --decode > src/main/resources/application.yml
          find src
      - name: Build JAR
        run: ./gradlew build

      - name: Deploy Prod use SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu/deploy"
          strip_components: 2

      - name: Transfer Deploy Script use SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: "deploy.sh"
          target: "/home/ubuntu/deploy"

